### ISSUE TITLE
MyBB Editor field covers Calender

### ISSUE THREAD

**Issue by Anon69420** [burnacid/MyBB-Form-Creator#103]
**Describe the bug**
The MyBB Editor field covers the drop down calendar

**To Reproduce**
See attached. Straight forward.

**Expected behavior**
The calendar to overlap the MyBB Editor instead of the other way around

**Desktop (please complete the following information):**
 - MyBB version: 1.8.15
 - Plugin version: 2.5.0
 - PHP version: 5.4.45-0+deb7u14
 - MySQL version: MySQLi 5.5.60

![3e9742a5e4b732967653562abf1e6b8b](https://user-images.githubusercontent.com/43067376/49671868-32737800-fa61-11e8-8e18-01ec73902e62.png)

**Comment by burnacid** [comment]
Please add this to jquery.sceditor.mybb.css

```
#ui-datepicker-div {
    z-index: 5!important;
}
```

**Comment by burnacid** [comment]
Added fix to dev branch
