### ISSUE TITLE
Allow users to add thread title

### ISSUE THREAD

**Issue by Admixing** [burnacid/MyBB-Form-Creator#106]
I’ve used this in the past, not now, and I always thought it would be a good edition to allow users to put their own thread title. In a sense this could be used in an open forum for users to submit News etc.

**Comment by burnacid** [comment]
You already can. Edit the form templates. And set the subject to one of the fields values

**Comment by burnacid** [comment]
It's not a workarround. There are alot of options people might not think of. It's just a matter of finding how to do what you want to do
