### ISSUE TITLE
Captcha field not working

### ISSUE THREAD

**Issue by Dr4inder** [burnacid/MyBB-Form-Creator#109]
The captcha field is not working anymore.

**Comment by burnacid** [comment]
Your message is very unspecific please explain more

**Comment by Dr4inder** [comment]
ive selected a captcha field. but in the form there is just an empty space

**Comment by burnacid** [comment]
That doesn't tell me much. Is Captcha enable for your forums?
The plugin uses the default captcha the forum is configured for. If you have not configured captcha it won't work

**Comment by Dr4inder** [comment]
oh ok i didnt know that. thx :)
