### ISSUE TITLE
Background Layer Missing on Date Field Calendar

### ISSUE THREAD

**Issue by Petepler** [burnacid/MyBB-Form-Creator#110]
**Describe the bug**
When using the Date field in the form entry, the background layer for the calendar appears to be missing so when it overlays, the form is the background. Tested on multiple themes and two different forums with all the same results.

**To Reproduce**
1. When in the form entry click on the date field
2. See error.

**Expected behavior**
It would be expected that there would be a plain white background behind the calendar text to make it more visible.

**Desktop (please complete the following information):**
 - MyBB version: 1.8.20
 - Plugin version: 2.6.0
 - PHP version: 7.2.15
 - MySQL version: MySQLi 5.6.41
--

![Calendar Bug](https://user-images.githubusercontent.com/48491455/54224881-d0e3ff00-44d0-11e9-9f75-fd2a4323d1b3.png)

**Comment by burnacid** [comment]
You are missing the CSS for the jQuery. Did you just install the plugin or did you do something else?

https://github.com/burnacid/MyBB-Form-Creator/blob/master/inc/plugins/formcreator/jquery-ui.css

This is the CSS please add it. During installation of the plugin this is normally added.

**Comment by Petepler** [comment]
I installed it by uploading the directories in the UPLOAD folder to myBB root. I located the .css file in myBB/inc/plugins/formcreator. Is that where the file needs to reside or does taht need to be moved to the JScripts folder?

**Comment by Petepler** [comment]
I ran a fresh install of MyBB and a fresh install of Form Creator and found that it worked fine. I am guessing that one of the themes installed edits a file that you use for the calendar. I am going to explore this more and will report back here.

**Comment by Petepler** [comment]
Deactivated Form Creator and reactivated it. Seems to be working now with Default and add-on themes.

**Comment by burnacid** [comment]
If you installed a new theme after installing the plugin you need to reinstall the plugin indeed

**Comment by Petepler** [comment]
I have run through several tests and haven't had the issue again. I think we can probably mark this resolved through refresh after theme install.
