### ISSUE TITLE
Warning message and can't create appplication

### ISSUE THREAD

**Issue by sfkandersen** [burnacid/MyBB-Form-Creator#117]
**Describe the bug**
Warning [2] urlencode() expects parameter 1 to be string, array given - Line: 136 - File: C:\Servers\Website\htdocs\form.php PHP 7.3.2 (WINNT)

C:\Servers\Website\htdocs\form.php | 136 | urlencode
-- | -- | --

**To Reproduce**
1. Go to 'https://theunitygaming.co.uk/form.php?formid=4'
2. Fill out form
3. Send

**Expected behavior**

**Desktop (please complete the following information):**
 - MyBB version: Latest!
 - Plugin version: 2.6.3
 - PHP version: 7.3.2
 - MySQL version: mysqlnd 5.0.12

**Please add an export of your form if the issue is within processing the form**
[export form.txt](https://github.com/burnacid/MyBB-Form-Creator/files/3438287/export.form.txt)

**Comment by burnacid** [comment]
Probably due to the fix I implemented for the summary page.
For now best is to disable the summary page. I'll work on a fix a.s.a.p

**Comment by sfkandersen** [comment]
The issue seems to only show, when using the "Select single" option, so for now i just replaced them with "radio buttons" Which works just fine :)

**Comment by BouncingHitman** [comment]
Hey burnacid, seems like that urlencode ya added to fix that last issue I found is screwing ya over again, eh? Anyways, I was creating a form for my staff so we may keep track of player bank adjustments and upon reaching the summary page I ran into the same issue as OP.

**Here's the export code:**
`[{"name":"Compensation\/Bank Notes","active":"1","fid":"22","tid":"0","overridebutton":"1","class":"","settings":{"allowedgidtype":"-1","customdenied":"","limitusage":"0","pmusers":"","prefix":"0","uid":"","customsuccess":"","signature":"0","posticon":"0","showsummary":"1","summaryparsed":"1","customsummary":"","width":"","labelwidth":"","allowedgid":[""],"pmgroups":[""]},"subjecttemplate":"{$fieldvalue[75]} | {$fieldvalue[71]} | {$fieldvalue[72]}","messagetemplate":"","fields":[{"fieldid":"68","name":"Administrator's name:","description":"The staff member who initiated the adjustment.","type":"1","default":"","required":"1","order":"0","class":"","settings":{"placeholder":"","maxlength":"0","regex":"","regexerror":"","size":""}},{"fieldid":"71","name":"Player's name:","description":" Name of the player receiving the adjustment","type":"1","default":"","required":"1","order":"1","class":"","settings":{"placeholder":"","maxlength":"","regex":"","regexerror":"","size":""}},{"fieldid":"72","name":"Amount:","description":"Amount that's being deducted or added.","type":"1","default":"","required":"1","order":"2","class":"","settings":{"placeholder":"0","maxlength":"","regex":"","regexerror":"","size":""}},{"fieldid":"73","name":"Deposit or withdrawal?","description":"","type":"5","default":"","required":"1","order":"3","class":"","settings":{"options":"Deposit\r\nWithdrawal"}},{"fieldid":"75","name":"Type of adjustment:","description":"","type":"3","default":"","required":"1","order":"4","class":"","settings":{"options":"Compensation\r\nDisciplinary Action\r\nOther"}},{"fieldid":"76","name":"Query notes:","description":"","type":"15","default":"","required":"0","order":"5","class":"","settings":{"rows":""}},{"fieldid":"77","name":"Submit","description":"","type":"11","default":"","required":"0","order":"6","class":"","settings":null}]}]`

Thanks again for working hard and making this amazing plugin free!

**Comment by burnacid** [comment]
I know I havent got time to fix it yet.

**Comment by burnacid** [comment]
Pushed a fix to development branch. Could you please upload the changed file and test if this has the propper result @BouncingHitman or @sfkandersen

**Comment by burnacid** [comment]
Pushed version to Extend
