### ISSUE TITLE
I'm not understanding this function...

### ISSUE THREAD

**Issue by Walter-Correa** [burnacid/MyBB-Form-Creator#121]
Hello.
I'm trying to use the Usage limit function, but not understand how this work.

**Comment by burnacid** [comment]
It limits how many time each user can use the form. It logs a record in the database of usage.
Can you tell me what you do not understand?

**Comment by Walter-Correa** [comment]
Ok. This usage limit is for each form, right?  It would be very useful if you had a posting limit for each form.  This helps a lot in forums that only 1 post is allowed per user.  If the post is moved or deleted, the user could post again.
