### ISSUE TITLE
form tolerates multiple submits

### ISSUE THREAD

**Issue by SvePu** [burnacid/MyBB-Form-Creator#125]
If you hit the browser back button you can send a filled form more than once. So you can generate multiple threads with the same content quickly.

A duplicate check would be nice and safe.

**Comment by burnacid** [comment]
I've used the default MyBB flooding detection which checks if a users last post or pm. Which is limited by the MyBB Settings if anti flooding is enabled. Can you please try if this is a sollution for you.

Download https://github.com/burnacid/MyBB-Form-Creator/blob/V2.6.5/form.php
And upload it to the root of your forums

**Comment by SvePu** [comment]
Thx...I'll try it.

**Comment by burnacid** [comment]
Released v2.6.5
