### ISSUE TITLE
Form pages seem to have CSS bugged out

### ISSUE THREAD

**Issue by Traidable** [burnacid/MyBB-Form-Creator#127]
It appears my forms are no longer showing up with my theme. It was working perfectly yesterday, and I did alter a bit of code regarding width of the content/containers of my actual theme. But since then, I checked the form and now it appears as such:

[Imgur Link to Preview of Form Pages](https://i.imgur.com/gQckWWY.png)

**To Reproduce**
1. Visit my webpage cf-dnd.com/forum
2. Click on the Transfer button on the menu, for example of one of the forms.
3. See page's layout / code bugging.

**Expected behavior**
Normally, the page looked fine. It showed as part of the regular theme I'm using, with all styling as intended. But now it is showing as above preview.

**Desktop (please complete the following information):**
 - MyBB version: 1.8.24
 - Plugin version: 2.6.5
 - PHP version: 7.3.21
 - MySQL version: MySQLi 5.6.49

Thanks for any help in advance!

**Comment by burnacid** [comment]
Hi

It's hard for me to tell you what broke this. You said you changed some template. Please send me what you changed. Than I can check what possibly is missing

**Comment by Traidable** [comment]
So, I am quite new at coding and such. I did alter a couple places in the Global CSS file, but I don't think I altered anything in the Templates at all, actually. But I included my full Global CSS, plus two Form Creator templates that may have something to do with it?

Perhaps maybe I can re-upload something to return it to a default states, without affecting my current forms?

[global.txt](https://github.com/burnacid/MyBB-Form-Creator/files/5396182/global.txt)
[formcreator.txt](https://github.com/burnacid/MyBB-Form-Creator/files/5396183/formcreator.txt)
[formcreator_container.txt](https://github.com/burnacid/MyBB-Form-Creator/files/5396184/formcreator_container.txt)

**Comment by Traidable** [comment]
I have no idea how this stuff works, BUT, removing the Captcha field from the form fixed it! Thank you for your help!
