### ISSUE TITLE
Import with Usages SQL error

### ISSUE THREAD

**Issue by burnacid** [burnacid/MyBB-Form-Creator#130]
**Describe the bug**
While importing a form with usage it will generate an SQL error

MyBB has experienced an internal SQL error and cannot continue.

If you're a visitor of this website, please wait a few minutes and try again. If this problem persists, please contact the site owner.

If you are the site owner, please check the MyBB Documentation for help resolving common issues, or get technical help on the MyBB Community Forums.

**Desktop (please complete the following information):**
 - MyBB version: 1.8.27
 - Plugin version: 2.6.5
 - PHP version: 7.3.28
 - MySQL version: MariadB 10.5.11

**Please add an export of your form if the issue is within processing the form**

**Comment by RyanTheDev12** [comment]
I am having the same issue. Any updates?

**Comment by RyanTheDev12** [comment]
I've tried the hotfix and it still seems to not work.
![image](https://user-images.githubusercontent.com/44126500/193146804-d5a46c23-3200-4a30-9c78-410556045618.png)

**Comment by burnacid** [comment]
Can you please download this hotfixed file and upload it to /admin/modules/config of your MyBB forums

https://github.com/burnacid/MyBB-Form-Creator/tree/hotfix/import-usage/admin/modules/config

This should resolve it. Please let me know your result

**Comment by burnacid** [comment]
Included in v2.6.6
