### ISSUE TITLE
Form Ideas

### ISSUE THREAD

**Issue by LewisHolt** [burnacid/MyBB-Form-Creator#14]
Hi there, this is a list of ideas for possible future implementation to this form plugin. 

## Form Ideas

1. Ability to 'override' a categories 'new thread' button with a new form button instead. 

2. Date field (Adds a date field with a little calendar popup)

3. Thread titles form input (ability to customise the generated thread title for that form and to put form 
field input data into the title e.g {form_answer1} could go into the title field)

4. Ability to style each form output individually with BB Code.

5. Ability to set form poster/pmer user (e.g you want all responses submitted on form A to be posted by the bot account and not the person who submitted the form)

6. Ability to limit the amount of times users can submit a form. 

7. Form Descriptions (HTML allowed) The ability to add a message beneath the form title. 

8. Preview - The ability to preview the output of the form before submitting it. (Would go next to Submit)

Will add more when I think of some.

**Comment by burnacid** [comment]
Will be looked at after the initial release. Suggestions are do-able

**Comment by burnacid** [comment]
Splitted the suggestion in to single issues for easier tracking of status

#20 
#21 
#22 
#23 
#24 
#25 

As for suggesion 7 this is already possible with a HTML block as field

**Comment by burnacid** [comment]
All the suggestions are done or there is another issue for it open. So I'll close this
