### ISSUE TITLE
Prefixes?

### ISSUE THREAD

**Issue by LewisHolt** [burnacid/MyBB-Form-Creator#19]
Could we have the ability added to select a prefix for the form's thread output?

Would be a nice little thing. (Made a different post so you could slot this one either in V1 or V2 with a clear understanding of what it is)

**Comment by burnacid** [comment]
Will try and put it within V1
Do you like to be able to set the prefex of the thread or the user of the forum able to select a prefix?

**Comment by LewisHolt** [comment]
Hm.

The prefix should be set in the Process Options just below the 'Post within forum' field, that seems like the most straightforward. Would the plugin grab all the prefixes that can be used inside that forum or just every single one that exists on the board?

The ability to select a prefix while putting information into the form itself could be pretty cool too. I've never actually considered selecting a prefix as one of the forms fields before. Up to you whether you want to implement it though.

**Comment by burnacid** [comment]
I'll add this one to v1. I'll add the ability to select a prefix as a field in v2.
It would probably show all prefixes.

**Comment by burnacid** [comment]
Feature added in DEV branch 2951d17e12ae5354c13c2a7fffb6008d751149e8
