### ISSUE TITLE
Import/Export Forms?

### ISSUE THREAD

**Issue by LewisHolt** [burnacid/MyBB-Form-Creator#29]
Do you think we could have the ability to export/import forms?

Say you want to export a form to use on another website having the ability to export/import forms would do that.

**Comment by burnacid** [comment]
Yea that could be made yet I do not really see a direct reason to im/export. Would be just as easy as a database query. Most people will only have 1 board.

I'll think abput it

**Comment by LewisHolt** [comment]
Could be used for backup/sharing purposes also.

**Comment by burnacid** [comment]
I'll have to do this after all because updating to a new version most likely requires a reinstallation

**Comment by burnacid** [comment]
Done for testing in 2.0 branch

**Comment by burnacid** [comment]
Need to still make a way so the template still works after import

**Comment by burnacid** [comment]
Fixed in latest commit of v2.0-dev
