### ISSUE TITLE
Administrator Logs

### ISSUE THREAD

**Issue by LewisHolt** [burnacid/MyBB-Form-Creator#31]
Hi there,

I just noticed that the Administrators Log's information for the Form Creator plugin hasn't really been stylised. 

http://i.imgur.com/19q6Up7.png

**Comment by burnacid** [comment]
Yea it's something I did not prioritize. It contains basic info so a skilled admin can still relate but for the rest it is pretty shit ;) will add it to the to-do for 2.0

**Comment by burnacid** [comment]
Can you describe what kind of formatting you are looking for?

**Comment by chack1172** [comment]
#46

**Comment by burnacid** [comment]
Ready in development branch for testing

**Comment by burnacid** [comment]
Released to V2.1.0
