### ISSUE TITLE
Moderation issue (admin approval forums)

### ISSUE THREAD

**Issue by thelovelyone** [burnacid/MyBB-Form-Creator#36]
"If the specific forum requires moderation (thread approval) and once you submit the form, it opens a new page with _The specified thread does not exist_, however i think it should bring u to index and telling u that it has to be approved instead of does not exist, whatever."

**Comment by burnacid** [comment]
Bug tested. Can be replicated

**Comment by burnacid** [comment]
Will be fixed in v2.0
