### ISSUE TITLE
No submit button? 

### ISSUE THREAD

**Issue by hpadmin623** [burnacid/MyBB-Form-Creator#38]
![capture](https://cloud.githubusercontent.com/assets/28683076/26031903/f35bc424-3838-11e7-83a9-4cba0c0bf610.PNG)

Whenever I go to the form, it doesn't have a submit button? Am I doing something wrong?

**Comment by burnacid** [comment]
Yes add a field with the time Submit Button ;)

**Comment by hpadmin623** [comment]
Thank you XD I am so use to IP Board. Appreciate it!
