### ISSUE TITLE
Overriding thread button

### ISSUE THREAD

**Issue by thelovelyone** [burnacid/MyBB-Form-Creator#40]
Hello,

after enabling "Override post button", the style of the new thread button changed (default mybb). I am using a custom one. Is it somehow possible to avoid this?

**Comment by burnacid** [comment]
Change the template. Copy and paste the 

forumdisplay_newthread to formcreator_thread_button
showthread_newreply to formcreator_thread_newreply
showthread_newreply_closed to formcreator_thread_newreply_closed
showthread_newthread to formcreator_thread_newthread

I can't deal with every other custom template. The plugin is templated and can be changed through there.

**Comment by burnacid** [comment]
No further response. Issue closed
