### ISSUE TITLE
Select multiple field improvement

### ISSUE THREAD

**Issue by thelovelyone** [burnacid/MyBB-Form-Creator#41]
I think it would be better to have an other kind of multiple select which doesn't require ctrl, but where you have checkboxes for example.

Current one is not very user-friendly imo.

**Comment by burnacid** [comment]
How about you use the checkbox field...?

**Comment by thelovelyone** [comment]
True, kinda overlooked the checkboxes, thanks.

As for the checkboxes:
Is this hover normal? https://i.gyazo.com/11998d4962f4815bd8626813601b7a96.gif

Shouldn't it only only get blue at the one you hover?

**Comment by burnacid** [comment]
Check you own CSS or jQuery. It's not caused by the plugin.
