### ISSUE TITLE
Attachment field

### ISSUE THREAD

**Issue by F4aR** [burnacid/MyBB-Form-Creator#45]
Is it possible to integrate a field for attachments in the future?

**Comment by Kai-Holmes** [comment]
I don't believe I can show support for ideas without replying, so I was just going to say that I seriously support this idea and think it would vastly expand the uses for the extension.

**Comment by burnacid** [comment]
I've made a Commit to the dev branch. Want to ask you if you would be so kind to test it see it if works for you. It tags into the Attachement system of MyBB.

**Comment by burnacid** [comment]
Released to V2.1.0
