### ISSUE TITLE
Unable to close, delete threads that are made.

### ISSUE THREAD

**Issue by TheDocter** [burnacid/MyBB-Form-Creator#51]
I was testing out the form creator system to create a thread. I am unable to close or delete the test thread. I receive the following error.

> Sorry, but you did not select any threads to perform inline moderation on, or your previous moderation session has expired (Automatically after 1 hour of inactivity). Please select some threads and try again.

I've tried to re login to the website as well.

**Comment by TheDocter** [comment]
My fault for not trying some other methods. Sorry for the post.

**Comment by burnacid** [comment]
No problem thanks for contacting
