### ISSUE TITLE
Add placeholder and maxlength...

### ISSUE THREAD

**Issue by Walter-Correa** [burnacid/MyBB-Form-Creator#58]
It is very important to have the options: Maxlength and Placeholder for Textbox and Textarea.

**Comment by burnacid** [comment]
What do you mean by Placeholder textbox en textarea?

**Comment by Walter-Correa** [comment]
<... **placeholder**="Enter your text here..." **maxlength**="500">

**Comment by burnacid** [comment]
Ready for release v2.2 coming soon
