### ISSUE TITLE
Fixes in form.php

### ISSUE THREAD

**Issue by Walter-Correa** [burnacid/MyBB-Form-Creator#60]
**The original code**(not working):

//Thread in Forum
**...**
// Set up the thread options
                        $new_post['options'] = array(
                            "signature" => 'yes',
                            "emailnotify" => 'no',
                            "disablesmilies" => 'no');

**Changed code**(working fine):
// Thread in Forum
**...**
// Set up the thread options
                        $new_post['options'] = array(
                            "signature" => '0',// 0 - Disable | 1 - Enable
                            "subscriptionmethod" => '',// ''- No subscribe | 'None' - Subscribe, but no notifications | 'email' - Subscribe with Email notifications | 'pm' - Subscribe with PM notifications
                            "disablesmilies" => '0');// 0 - Disable | 1 - Enable

The same changes is needed for:
// Post in Thread
**...**
// Set up the thread options
                        $new_post['options'] = array(
                            "signature" => '0',// 0 - Disable | 1 - Enable
                            "subscriptionmethod" => '',// ''- No subscribe | 'None' - Subscribe, but no notifications | 'email' - Subscribe with Email notifications | 'pm' - Subscribe with PM notifications
                            "disablesmilies" => '0');// 0 - Disable | 1 - Enable

**Comment by burnacid** [comment]
Thanks added. Will be in release V2.2
