### ISSUE TITLE
Portuguese-Brazil Translation | By Walter_Correa

### ISSUE THREAD

**Issue by Walter-Correa** [burnacid/MyBB-Form-Creator#61]
Hello!
Here is my small contribution to this important and useful project!
I would like to say that I really like this plugin!
Keep improving it more and more!
**Thank you!**

**Direct Download:** https://dl.dropboxusercontent.com/s/yfq5ioqf3e8ae3c/FormCreator_PT_BR_Translation.zip

**Comment by burnacid** [comment]
Will be added to next release. Misses 1 " but well ;)
Great job translating thanks for the support of the plugin

**Comment by Walter-Correa** [comment]
Thank you! But tell me which line I forgot the ".

**Comment by burnacid** [comment]
Line 28 of admin/config_formcreator.lang.php

```
$l['fc_edit_field_desc'] = "Editar um Campo;
````

It should be

```
$l['fc_edit_field_desc'] = "Editar um Campo";
```

**Comment by Walter-Correa** [comment]
Ohh hahaha, sorry! Has been fixed in the dropbox file too! Thanks for all!

**Comment by burnacid** [comment]
Next version you will have to add a few translations though ;)

**Comment by burnacid** [comment]
Please add the following lines. Numbers are the line numbers

Admin Language file

```
45 $l['fc_output_template_success'] = "The output template has succesfully be changed";
58 $l['fc_limitusage'] = "Usage limit";
59 $l['fc_limitusage_desc'] = "Enter the maximun number of times a user can fill in the form (0 = unlimited).";
80 $l['fc_custom_success_page'] = "Custom success page";
81 $l['fc_custom_success_page_desc'] = "Set an URL the user will be redirected to after completing the form.";
94 $l['fc_other'] = "Other";
95 $l['fc_reference_number'] = "Reference Number";
122 $l['fc_placeholder'] = "Placeholder";
123 $l['fc_field_placeholder_desc'] = "Write a payload for the short hint that is displayed in the input field before the user enters a value.";
124 $l['fc_maxlength'] = "Max length";
125 $l['fc_field_maxlength_desc'] = "Enter the maximum lenght of characters the user can enter. (0 = unlimited)";
149 $l['fc_field_example'] = "Field example";
177 $l['fc_export_usagelog'] = "Export Usage Log";
178 $l['fc_export_usagelog_desc'] = "Do you like to export the usage history? Set this to 'OFF' if you are going to import this on other forums.";
```

Normal Language file

```
12 $l['fc_access_denied'] = "Access Denied";
13 $l['fc_form_disabled_title'] = "Form Disabled";
14 $l['fc_limit_reached_title'] = "Form Limit Reached";
15 $l['fc_limit_reached'] = "You have reached the maximum form usage";
```

**Comment by Walter-Correa** [comment]
Wow! Nice... I'll add soon! I'am the official portuguese-br translator now hahahah Thanks!

**Comment by Walter-Correa** [comment]
Done! The **Direct Download:** https://dl.dropboxusercontent.com/s/yfq5ioqf3e8ae3c/FormCreator_PT_BR_Translation.zip

Was updated and translated!
NOTE: If I need use another way to update/change/send the translation, just tell me! 
Thanks!

**Comment by burnacid** [comment]
Well best way is just to make commits straight to github ofc

**Comment by burnacid** [comment]
Pushed to commit. Ready for V2.2

**Comment by burnacid** [comment]
Translation portal is live. Feel free to register ;)

http://translate.lenders-it.nl/engage/mybb-form-creator/?utm_source=widget

**Comment by Walter-Correa** [comment]
Nice! Registered, but more than one people can translate or edit a translated language?

**Comment by burnacid** [comment]
Only if I allow them to. You have been added as translator.
Plus it's full version controlled so changes can be reverted.

I'm trying to search for more translators to translate it in other languages. When it gets to much shit I'll search trusted reviewers who need to approve new suggestions

**Comment by Walter-Correa** [comment]
Ok! But why the portuguese language have (generated) after name?
The folder name of portuguese language for mybb is: portugues_brasil

**Comment by burnacid** [comment]
Yea it reads the languages from GitHub and commits changes there. Since I had your translation it "Generated" the language from that. That's the reason for the (generaged) the folder is still correct.

https://github.com/burnacid/MyBB-Form-Creator/commits/translations

**Comment by Walter-Correa** [comment]
Thank you very much, it was just a curiosity!
Congratulations on improving this project!
Support for translations is great now, thanks for everything!
