### ISSUE TITLE
Problem in class_formcreator.php

### ISSUE THREAD

**Issue by Walter-Correa** [burnacid/MyBB-Form-Creator#66]
Hello!
There is a small problem in line **1029** of the file **class_formcreator.php**, a reference to the field type **Select (Multiple)**:  `$output .= "<option value=''>- Select option -</option>";`

If the user does not select any option, even if it is a required field, in the output model we have: **Unknown**.

**My suggestion:** Remove this line, after all, is what I'm doing now, because it does not serve much. I think it's best to leave the first option in the list as default, so if the user does not select any option, the first option will be the default.

If you do not agree to remove and can fix this bug, I suggest adding the possibility to translate the text: `- Select option -`

**Thank you!**

**Comment by burnacid** [comment]
Will add to language file and make the required tag work correctly
