### ISSUE TITLE
Attachments Problem

### ISSUE THREAD

**Issue by dawidgiertuga** [burnacid/MyBB-Form-Creator#79]
I have some forms that need attachments, however, the attachments function doesn't seem to work. 
Whenever I submit a test form with some text and an attachment, the text appears without any problems, however, the attachment is gone. I've tried making the form a post in a forum as well as just having it messaged to certain user groups.
When I tried to use a custom output template, the attachment came up as text saying 'Unknown'.
I've also tried to use a clean installation of mybb 1.8.14, and the same thing happened.
I've also tried using the single attachment field as well as multiple attachments.

**Comment by burnacid** [comment]
Please try submitting the same attachment just through the normal way of creating a thread / post.

**Comment by dawidgiertuga** [comment]
Submitting attachments normally works without any issues

**Comment by burnacid** [comment]
Could you provide me with details of the test installation and the steps you are following to reproduce?

**Comment by dawidgiertuga** [comment]
Details:
<img width="1103" alt="screen shot 2018-02-12 at 13 22 21" src="https://user-images.githubusercontent.com/21983343/36098720-ee5a12d6-0ff7-11e8-8175-465939f44a08.png">
<img width="1111" alt="screen shot 2018-02-12 at 13 28 10" src="https://user-images.githubusercontent.com/21983343/36098916-af3c8704-0ff8-11e8-8f44-82aaa7fc0d93.png">

Steps to reproduce:

1. Crete new form (any settings) (posting within a forum and making it a PM have the same result)
2. Add a text box (single line)
3. Add an attachment filed (Single and multiple have the same result)
4. Add a submit button
5. Fill out the form and add an attachment 
<img width="1163" alt="screen shot 2018-02-12 at 13 33 35" src="https://user-images.githubusercontent.com/21983343/36099099-5f2d0dbe-0ff9-11e8-96b2-98b172bbe76d.png">

6. Submit
7. View the thread (edit window also shows no attachments)
<img width="1187" alt="screen shot 2018-02-12 at 13 34 14" src="https://user-images.githubusercontent.com/21983343/36099123-706f86a6-0ff9-11e8-99e5-fa06169e124a.png">
<img width="1191" alt="screen shot 2018-02-12 at 13 34 36" src="https://user-images.githubusercontent.com/21983343/36099153-862551e2-0ff9-11e8-8221-b6aab9ff0590.png">

**Comment by burnacid** [comment]
Mmm I'm having the same no clue why yet. Need to look into it.

**Comment by burnacid** [comment]
@dawidgiertuga Please test with the last commit of the Development branch if the issue is gone

**Comment by dawidgiertuga** [comment]
Thanks, the issue seems to be resolved.

**Comment by burnacid** [comment]
Pushing in V2.4.1
