### ISSUE TITLE
My account in Weblate was deleted?

### ISSUE THREAD

**Issue by Walter-Correa** [burnacid/MyBB-Form-Creator#83]
I tried to sign in but it looks like my account has been deleted.
I was translating the Portuguese language, I do not know if I was purposely removed.
I created an account again, but there is no permission to save the translations.

**Comment by burnacid** [comment]
Not on purpose not. My docker installation of weblate crashed. I'll reset you permissions.

**Comment by burnacid** [comment]
Should have the rights
