### ISSUE TITLE
Unable to create Thread

### ISSUE THREAD

**Issue by nobodyshome** [burnacid/MyBB-Form-Creator#84]
All my forms work besides one. When filling out a form and submitting it, the thread never gets made. However looking at the database the usage is logged, just a thread is never made.

If you need anything to help debug this, let me know and ill try to respond asap.

**Comment by nobodyshome** [comment]
Seems to be a length issue. When one of the options was selected it would never post.

**Comment by burnacid** [comment]
I need more detailed info then this. Please send me a link and on what option you thing the error exists.

**Comment by nobodyshome** [comment]
We are using the "Select (Single)" and when the option below was selected, form never made a thread:

**Comment by burnacid** [comment]
Please post an export of the form and tell me the exact actions to recreate the error

**Comment by nobodyshome** [comment]
`[{"name":"Transfer Request","active":"1","fid":"122","tid":"0","overridebutton":"1","class":"","settings":{"allowedgidtype":"1","allowedgid":["1","2","5","7"],"limitusage":"","pmusers":"","pmgroups":["4","78"],"prefix":"0","uid":"","customsuccess":"","signature":"0","posticon":"0","width":"60%","labelwidth":""},"subjecttemplate":"{$username} | {$fieldvalue[39]} to {$fieldvalue[40]}","messagetemplate":"[b]{$fieldname[38]}:[\/b] {$fieldvalue[38]}\r\n[hr]\r\n[b]{$fieldname[39]}:[\/b] {$fieldvalue[39]}\r\n[b]{$fieldname[40]}:[\/b] {$fieldvalue[40]}\r\n[hr]\r\n[b]{$fieldname[41]}:[\/b]\r\n{$fieldvalue[41]}\r\n","allowedgidtype":-1,"fields":[{"fieldid":"38","name":"Rank","description":"What is your current Rank?","type":"1","default":"","required":"1","order":"0","class":"","settings":{"placeholder":"","maxlength":"","regex":"","regexerror":"","size":""}},{"fieldid":"39","name":"Current Unit","description":"","type":"3","default":"","required":"1","order":"1","class":"","settings":{"options":"5th Battalion (The Rifles Regiment)\r\nJoint Helicopter Command (JHC)\r\nAJAX Squadron (Royal Tank Regiment)\r\n16th Medical Regiment (Royal Army Medical Corps)\r\n45 Commando (Royal Marines)\r\nSpecial Boat Service (SBS)"}},{"fieldid":"40","name":"Gaining Unit","description":"","type":"3","default":"","required":"1","order":"2","class":"","settings":{"options":"5th Battalion (The Rifles Regiment)\r\nJoint Helicopter Command (JHC)\r\nAJAX Squadron (Royal Tank Regiment)\r\n16th Medical Regiment (Royal Army Medical Corps)\r\n45 Commando (Royal Marines)\r\nSpecial Boat Service (SBS)"}},{"fieldid":"41","name":"Reason\/Remarks","description":"","type":"2","default":"","required":"1","order":"3","class":"","settings":{"placeholder":"","maxlength":"","regex":"","regexerror":"","cols":"","rows":"","resize":"1"}},{"fieldid":"42","name":"Separator","description":"","type":"8","default":"","required":"0","order":"4","class":"","settings":null},{"fieldid":"43","name":"Notice","description":"","type":"10","default":"","required":"0","order":"5","class":"","settings":{"html":"Once submitted your request will be reviewed by both your current and gaining unit Command Staff, once reviewed they will be in contact about the outcome of your request."}},{"fieldid":"44","name":"Submit","description":"","type":"11","default":"","required":"0","order":"6","class":"","settings":null}]}]`

Just import, fill out the form but select "16th Medical Regiment (Royal Army Medical Corps)" and the thread won't be made. Selecting any other option works.

**Comment by nobodyshome** [comment]
It may also do it when selecting "AJAX Squadron (Royal Tank Regiment)" but we haven't had chance to test. Did i do the export right?

**Comment by burnacid** [comment]
Seen the issue on my test bench. Need to review.

**Comment by burnacid** [comment]
You reached subject name limit the way you set it up. The max characters within the subject is 85 by MyBB standards.

I'll make a note to cut of the characters if there are to many but this won't be on a short notice.

**Comment by nobodyshome** [comment]
No worries, thanks for the awesome plugin. Glad to of helped.

**Comment by burnacid** [comment]
No problem good luck with JFC ;)

**Comment by burnacid** [comment]
Fixed
