### ISSUE TITLE
Attachment not working

### ISSUE THREAD

**Issue by Cyclone47** [burnacid/MyBB-Form-Creator#85]
Hello,

Uploading attachments does not seem to work.
When setting it to required( 

'Screenshot 1' is empty!
'Screenshot 2' is empty!

When setting it to not required it proceeds, but the attachments do not upload.

What I checked:
* Permission on uploads folder
* Max attachment size
* Allowed attachments
* Single attachment is the one I am testing

Edit: multiple attachments also says "is empty!"

**Comment by burnacid** [comment]
Please paste an export of the form so I can check the settings.

**Comment by Infinito47** [comment]
Might be related to https://community.mybb.com/thread-213472-post-1300866.html#pid1300866 Will report back soon!

**Comment by burnacid** [comment]
Oke, sounds plossible. Remember the attachments use the build-in feature of MyBB so

**Comment by Infinito47** [comment]
[{"name":"test","active":"1","fid":"61","tid":"0","overridebutton":"0","class":"","settings":{"allowedgidtype":"-1","limitusage":"","pmusers":"","prefix":"0","uid":"","customsuccess":"","signature":"0","posticon":"0","width":"","labelwidth":"","allowedgid":[""],"pmgroups":[""]},"subjecttemplate":null,"messagetemplate":null,"fields":[{"fieldid":"60","name":"test","description":"","type":"1","default":"","required":"1","order":"0","class":"","settings":{"placeholder":"","maxlength":"","regex":"","regexerror":"","size":""}},{"fieldid":"61","name":"test attachment","description":"","type":"13","default":"","required":"1","order":"1","class":"","settings":null},{"fieldid":"62","name":"submit","description":"","type":"11","default":"","required":"0","order":"2","class":"","settings":null}],"usage":[]}]

I'll post this for now until that attachment feature works better.
What's strange that posting attachments works fine in posts, just the displaying being broken. So I'm not sure if this is the same reason why it doesn't work @ Form Creator.

**Comment by Infinito47** [comment]
The attachment issue has been fixed. I still have the same issue with the form attachment.

**Comment by Infinito47** [comment]
Due to privacy reasons I won't post you a test account, but you could try: 
https://wowgasm-reloaded.org/forum/form.php?formid=5

I disabled e-mail verification for easy register.

Security questions: 
What's the short name for World of Warcraft?  - wow
What is the oposite faction of Alliance? - horde

**Comment by burnacid** [comment]
I can't recreate this on my test forum. So it is host specific.
The only way for me to investigate is to have access to your forums.

**Comment by burnacid** [comment]
Probably same as #93 closing this one
