### ISSUE TITLE
Translations page is not working

### ISSUE THREAD

**Issue by Walter-Correa** [burnacid/MyBB-Form-Creator#91]
Hello.
http://translate.lenders-it.nl/projects/mybb-form-creator/

**Comment by burnacid** [comment]
weblate keept dying on my so I killed it. I've recently tried to get it back up working on a clean debian client but it just doesn't want to. So sadly it's unavailible

**Comment by burnacid** [comment]
It's back running properly finally.
http://translate.lenders-it.nl

Feel free to recreate an account

**Comment by burnacid** [comment]
It worked for a total of 5 days. Then it broke again out of no where for no reason with no clear description how to fix it. Weblate is anoying so I can't be bothered to fix it. So sadly translation will have to go through PHP files and a push request on github if you like it to be included to the repo

**Comment by Walter-Correa** [comment]
Ok. I'am the oficial translator of the Portuguese language :)
