### ISSUE TITLE
Thread prefix from Form field

### ISSUE THREAD

**Issue by khyinn** [burnacid/MyBB-Form-Creator#94]
Hi,

One small addition to the plugin : set the thread prefix from a form field so the user can choose between some thread prefixes.

**Comment by khyinn** [comment]
Oh, just one more thing : in fact we should be able to select existing thread prefixes (for the forum where we are posting the thread) instead of using a form field, i think it's better and more simple because of prefixes permissions and prefixes styles...

**Comment by burnacid** [comment]
Well if I add this it will be that you can insert a selection of allowed prefix ID's the user can use.

**Comment by khyinn** [comment]
Nice :) Hope that you'll have some time to add this (and the other request i've made :D)

**Comment by burnacid** [comment]
Will be added to Version 2.5.0
